### ISSUE TITLE
Regarding Running With a Custom Dataset

### ISSUE THREAD

**Issue by aflah02** [Aolius/semi-fst#1]
Hey!
Congrats on the Great Paper
Can you please add some instructions on how to run this with a custom dataset/ how to format your own dataset for the code files? It would be really helpful!

**Comment by Aolius** [comment]
Hi, thank you for your interest in our work.
To use your own dataset for training, you may take a look at two dataset classes:
1. [T5Dataset](https://github.com/Aolius/semi-fst/blob/b4ba36fe930c0c59e9fd1efff92375da8d4e4895/utils/T5_dataset.py#L236) for loading parallel data. It takes as arguments two file paths representing the source data and target data.
2. [T5AugDataset](https://github.com/Aolius/semi-fst/blob/b4ba36fe930c0c59e9fd1efff92375da8d4e4895/utils/T5_dataset.py#L310) for loading unlabeled data. It accepts one file path representing the unsupervised data.

So basically you need three data files, source.txt, target.txt, and unlabeled.txt, each containing one sentence per line. In FST, source.txt, and target.txt contain the informal and formal sentences in training data, and unlabeled.txt is the unpaired informal sentences we collected. 

Just change the file paths in the `T5_Large_filter.py` (e.g. line 191-192) to your own data in the same format. You may also need to pretrain a new style classifier on your data for evaluation. Similarly, you can change line 102-111 in [texcnn_t5.py](https://github.com/Aolius/semi-fst/tree/master/classifier/textcnn_t5.py) and retrain the classifier as instructed in [Step 1](https://github.com/Aolius/semi-fst#1-pre-train-style-classifiers).

**Comment by aflah02** [comment]
Thanks a ton @Aolius for the comprehensive reply!
