### ISSUE TITLE
model comparison

### ISSUE THREAD

**Issue by xyiiinexg3** [Aolius/semi-fst#3]
> ∗ indicates that the model used training data from both domains and is not comparable to our model.

excuse me, i wanna know whether training data from GYAFC was used in your model.
i will appreciate it if you can reply me at your earliest convenience

**Comment by Aolius** [comment]
Hi, we did use the training data from GYAFC, but we have trained two models separately on the EM domain data and the FR domain data. Some work has combined the two domains to train a single model .

**Comment by xyiiinexg3** [comment]
Thank u~
